name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
    - run: ./gradlew arsc:build
    - run: ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target/
